USE auth_profiling;

CREATE TABLE IF NOT EXISTS Users (USERNAME VARCHAR(256) PRIMARY KEY NOT NULL,
                       PASSWORDHASH VARCHAR(256) NOT NULL,
                       EMAIL VARCHAR(256) NOT NULL,
			UNIQUE (USERNAME))
  ENGINE=INNODB;
